
#pragma once

//水平滚动条和垂直滚动条交点处位置冲突时的处理方式（水平滚动条优先，垂直滚动条优先，都不优先）
typedef enum ScrollHVConflictManage{
	ESHVCM_HORI = 1,ESHVCM_VERT,ESHVCM_NONE
}ESCROLLHVCONFLICTMANAGE;

//曲线颜色设置类型-- 按通道分色、按类型分色、按行分色、按列分色、按目标分色，默认颜色
typedef enum LineColorMode{
	ECM_BYCHANNEL,ECM_BYTYPE,ECM_BYROW,ECM_BYCOL,ECM_BYTARGET,ECM_DEFAULT
}ELINECLRMODE;

typedef struct BoxOutInParam
{
	CWnd* pWnd;
	BOOL bIn;
	BoxOutInParam(){
		pWnd = NULL;
		bIn = TRUE;
	}
}BOXOUTINPARAM;

typedef enum InsertSelect{
	EIS_BEFORE = 1,EIS_AFTER,EIS_LAST
}EINSERTSELECT;

typedef enum InsertType{
	EIT_STEP = 1,EIT_SEGMENT
}EINSERTTYPE;

struct tagMultiTempDataEx
{
	DWORD dwTime;     ///< 时间序号
	WORD wTargetData;///< 目标温度值
	WORD wT1Data;    ///< 第1路温度数据
	WORD wT2Data;	 ///< 第2路温度数据
	WORD wT3Data;	 ///< 第3路温度数据

	WORD wT1StartPoint; ///< 第1路温度整板扫描起点温度值
	WORD wT1EndPoint;   ///< 第1路温度整板扫描终点温度值
	WORD wT2StartPoint; ///< 第2路温度整板扫描起点温度值
	WORD wT2EndPoint;   ///< 第2路温度整板扫描终点温度值
	WORD wT3StartPoint; ///< 第3路温度整板扫描起点温度值
	WORD wT3EndPoint;   ///< 第3路温度整板扫描终点温度值
};
typedef CArray<tagMultiTempDataEx, tagMultiTempDataEx>	MultiTemperatureDataExArray;

typedef enum SamSortWay{
	ESSW_HORI,ESSW_VERT
}ESAMSORTWAY;

typedef enum SamSortDirection{
	ESSD_POSITIVE,ESSD_NEGATIVE
}ESAMSORTDIRECTION;

typedef enum ItemInfoType
{
	ITEMHOLEINFO = 1,ITEMSAMTYPE,ITEMSTDDENSITY,ITEMREPETITIVETUBE,ITEMSAMNAME,ITEMSAMID,ITEMPATIENTNAME,ITEMSEXUALITY,ITEMAGE,ITEMSAMCOLLECTDATE,
	ITEMSENDINGDOCTOR,ITEMSENDINGSECTION,ITEMANAMNESISNO,ITEMBEDNO,ITEMHOSPITALID,ITEMOUTPATIENTNO,ITEMREMARKS,ITEM_REPETITIVETUBETAG,ITEMNONE,ITEM_DATAANADLG_CBCRVSELECT,ITEM_DATAANADLG_CBTHRESELECT,
	ITEM_PRJBASE_CBPRJTYPE,ITEM_PRJBASE_EDPRJNAME,ITEM_SELECT_LANGUAGE,ITEM_CYSAMINFO_CB_SAMCATEGORY,ITEM_CYSAMINFO_ED_PRODUCTBN,ITEM_CYSAMINFO_ED_SAMCOUNT,
	ITEM_CYSAMINFO_ED_SAMSTATE,ITEM_CYSAMINFO_ED_COMMENT,ITEM_CYSAMINFO_ED_TESTITEM,ITEM_CYSAMINFO_DT_COLLECTDATE,ITEM_CYNORMSET_ED_CLIENT,ITEM_CYNORMSET_ED_CPADR
}EITEMINFOTYPE;

typedef enum ItemInfoDataType{
	EIIDT_NONE,EIIDT_STRING,EIIDT_INT,EIIDT_DOUBLE,EIIDT_SEXUALITY
}EITEMINFODATATYPE;

typedef enum CtrlState{
	ECS_NORMAL,ECS_HOVER,ECS_SELECTED,ECS_DISABLE
}ECTRLSTATE;





